name: "Labels: Approved"

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    # Frontier: repo changed (space-wizards/space-station-14 < new-frontiers-14/frontier-station-14)
    if: ${{ (github.repository == 'AphelionDevelopment/Wolfgate') && (github.event.review.state == 'APPROVED') }} # Wolfgate
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: tspascoal/get-user-teams-membership@v3
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: "maintainers" # Wolfgate: AphelionDevelopment org team
        GITHUB_TOKEN: ${{ secrets.LABELER_PAT }}
    - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Approved"
